# This is a basic workflow to help you get started with Actions

name: Deploy Environment

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment you want to deploy to.'
        type: environment
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Echo Variable associated to the environment
        run: echo ${{ vars.ENVIRONMENT }}

