name: Masking Workflow Input

on:
  workflow_dispatch:
    inputs:
      secret_password:
        type: string
        required: true
        description: Password that should be obfuscated in the workflow logs

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Masking inputs
        run: |
          SECRET_PASSWORD=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.secret_password' )
          echo "::add-mask::$SECRET_PASSWORD"
          echo "This is my password: $SECRET_PASSWORD" 
